### ISSUE TITLE
How to get same translated image as source without adding any extra or new objects

### ISSUE THREAD

**Issue by IqraNosheen786** [xXCoffeeColaXc/DiffusionBasedImageTranlationWithGradientGuidance#1]
Hi, based on the results attached, it is
still changing the original architecture of the source image and adding extra objects to the translated image? https://github.com/xXCoffeeColaXc/DiffusionBasedImageTranlationWithGradientGuidance/blob/main/res/to_night.png

**Comment by xXCoffeeColaXc** [comment]
@IqraNosheen786 Hello, yes it does. I will look into it. By the end of the summer, I think, I will have a solution for translating with almost perfect semantic consistency!

**Comment by IqraNosheen786** [comment]
@xXCoffeeColaXc I am also actively exploring the use of diffusion models for domain adaptation tasks. My goal is to make virtual data more realistic while preserving its original structure. Looking forward to your solution.

**Comment by xXCoffeeColaXc** [comment]
@IqraNosheen786  Hello! I'm currently refactoring my code (it was so awful) and rebased it to this repo: [https://github.com/xXCoffeeColaXc/WeatherConverter](https://github.com/xXCoffeeColaXc/WeatherConverter)
