### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by Lzyin** [xXCoffeeColaXc/DiffusionBasedImageTranlationWithGradientGuidance#2]
Thank you for your work! 

I am interested in knowing whether it is feasible to reproduce the domain adaptation segmentation results presented in the paper？

**Comment by xXCoffeeColaXc** [comment]
@Lzyin Thank you! I hope so it will be feasible :D 
Currently I'm refactoring my code (it was so awful) and rebased it to this repo: [https://github.com/xXCoffeeColaXc/WeatherConverter ](https://github.com/xXCoffeeColaXc/WeatherConverter)
