### ISSUE TITLE
The project team

### ISSUE THREAD

**Issue by yisun98** [xXCoffeeColaXc/DiffusionBasedImageTranlationWithGradientGuidance#3]
I am also trying to reproduce this work. I'm surprised that you're also doing this. Would it be convenient for you to provide the training code for SGG? I will try to complete and improve it based on your code. You can add me to this interesting project. Best wishes.

**Comment by xXCoffeeColaXc** [comment]
@yisun98 Hey! I'm happy to hear that. I'm currently refactoring my code (it was so awful) and rebased it to this repo: [https://github.com/xXCoffeeColaXc/WeatherConverter](https://github.com/xXCoffeeColaXc/WeatherConverter)
Under seg_model you can find the current segmentation model, which will be used in SGG. Keep on eye on it!
